version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # Followed instructions from https://hub.docker.com/_/microsoft-mssql-server
    # Platform linux/amd64 is to fix it trying to run linux/arm64/v8 on Apple Silicon Macs
    # Presumably that requires Rosetta to be installed https://support.apple.com/en-us/HT211861
    restart: always
    platform: linux/amd64
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      # Password needs to include at least 8 characters of at least three of these four categories: 
      # uppercase letters, lowercase letters, numbers and non-alphanumeric symbols.
      MSSQL_SA_PASSWORD: Qwerty123
    volumes:
      - ./dev/powin-db:/scripts/
    ports:
      - 1433:1433

  app:
    build: .
